# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: postgres-pvc

# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim # Sets name of PVC
  namespace: digiboard-ns
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany # Sets read and write access
  resources:
    requests:
      storage: 1Gi # Sets volume size
