apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: dev
  labels:
    app: postgres
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
