# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: postgres-pv

# spec:
#   capacity:
#     storage: 1Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: standard
#   # hostPath:
#   #   path: "C:\Users\\ndjoc\workspace"
#   local:
#     path: "C:\\Users\\ndjoc\\workspace" # Double backslashes are needed on Windows
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#         - matchExpressions:
#             - key: kubernetes.io/os
#               operator: In
#               values:
#                 - windows

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: postgres-pv
# spec:
#   capacity:
#     storage: 1Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: local-storage
#   local:
#     path: /c/Users/ndjoc/workspace/minikube-temp
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#         - matchExpressions:
#             - key: kubernetes.io/hostname
#               operator: In
#               values:
#                 - docker-desktop

kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume # Sets PV's name
  namespace: digiboard-ns
  labels:
    type: local # Sets PV's type to local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  # hostPath:
  #   path: "/mnt/data"
