import DashboardBreadcrumb from "@/components/breadcrumb/DashboardBreadcrumb";
import DashboardCards from "@/components/cards/DashboardCards";
import BalanceChart from "@/components/charts/EComBalanceChart";
import ECosts from "@/components/charts/EComCostChart";
import ECostRecents from "@/components/charts/EComCostRecents";
import RecentOrders from "@/components/charts/RecentOrders";
import WeeklySalesRecap from "@/components/charts/WeeklySalesRecap";

import SalesAnalytics from "@/components/dashboard/SalesAnalytics";
import Footer from "@/components/footer/Footer";
import Head from "next/head";
import { useState } from "react";

const SalesAnalyticsWrapper = () => (
  <>
    <SalesAnalytics />
    <WeeklySalesRecap />
    <RecentOrders />
  </>
);

const ECostsWrapper = () => (
  <>
    <ECosts />
    <ECostRecents />
  </>
);

export default function Home() {
  const [displayedComponent, setDisplayedComponent] = useState(null);

  const handleLinkClick = (component) => {
    setDisplayedComponent(component);
  };

  return (
    <>
      <Head>
        <title>Digiboard - eCommerce Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="assets/favicon.png" />
      </Head>
      <div className="main-content">
        <DashboardBreadcrumb title={"eCommerce Dashboard"} />
        <DashboardCards onLinkClick={handleLinkClick} />
        <div className="row">
          {displayedComponent === "salesAnalytics" && <SalesAnalyticsWrapper />}
          {displayedComponent === "marketingExpenses" && <ECostsWrapper />}
          {displayedComponent === "weeklybalanceRecap" && <BalanceChart />}
        </div>
        <Footer />
      </div>
    </>
  );
}
