apiVersion: apps/v1
kind: Deployment
metadata:
  name: digiboard

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: digiboard
  template:
    metadata:
      labels:
        app: digiboard
    spec:
      containers:
        - name: digiboard
          # image: { { .Values.image } }
          image: 755840619199.dkr.ecr.us-east-2.amazonaws.com/digiboard:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          # readinessProbe:
          #   httpGet:
          #    path: /
          #    port: 8080
