apiVersion: apps/v1
kind: Deployment
metadata:
  name: digiboard
  namespace: digiboard-ns
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: digiboard
  template:
    metadata:
      labels:
        app: digiboard
    spec:
      containers:
        - name: digiboard
          image: {{ .Values.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          # readinessProbe:
          #   httpGet:
          #    path: /
          #    port: 8080
