name: Feature branch

on:
  push:
    branches: ["feature**"]
jobs:
  build_branch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout on the workdir
        uses: actions/checkout@v3

      - name: Set up JDK 17 
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Get node_modules cache
        uses: actions/cache@v3.0.2
        id: node_modules 
        with:
          path: "**/node_modules"
          #path: "**/node_modules **/next/cache"
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}-${{ steps.node.outputs.version }}
      - name: build artifact
        run: mvn -B package
