name: Feature branch

on:
  push:
    branches: ["feature**"]

jobs:
  build_branch:
    runs-on: ubuntu-latest

    steps:
      - name: checkout on the workdir
        uses: actions/checkout@v3

      - name: Set up JDK 17 
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: build artifact
        run: mvn -B package
