name: Main branch workflow

on:
  pull_request: # only pull request
    branches: [ "main" ]
jobs:

  build_branch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout on the workdir
        uses: actions/checkout@v3

      - name: Set up JDK 17 
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven


      - name: Get node_modules cache
        uses: actions/cache@v3.0.2
        id: node_modules 
        with:
          path: "**/node_modules **/next/cache"
          key: ${{ runner.os }}-build-cache-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: build artifact
        run: mvn -B package
#   deploy:
#     runs-on: ubuntu-latest
#     needs: build_branch
#     steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.27.0'
        id: install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'false'

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: digiboard
          IMAGE_TAG: latest
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Update kube config
        run: aws eks update-kubeconfig --name "arn:aws:eks:us-east-2:755840619199:cluster/tf-cluster"

      - name: Deploy java helm chart to EKS
        run: |
          helm install java ./java-chart