name: 1st workflow

on:
  push:
    branches:
      - main
jobs:
  premier_job:
    runs-on: ubuntu-latest
    steps:
      - name: another hello word command
        run: echo "another hello word command"
        shell: bash