spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgresdb
    driver-class-name: org.postgresql.Driver
    username: admin
    password: psltest
  liquibase:
    change-log: classpath:/db/changelogs/master-cl.yaml

springdoc:
  api-docs:
    path: /digiboard-api-docs-json #http://localhost:8080/digiboard-api-docs-json -> OpenAPI documentation in json format
  packages-to-scan: media.soft.controller
  swagger-ui:
    path: /digiboard-api-docs #http://localhost:8080/digiboard-api-docs -> Swagger documentation
    tryItOutEnabled: true
    operationsSorter: method
    tagsSorter: alpha
    filter: true
