spring:
  datasource:
    url: jdbc:mysql://mydb.cigqf7ww5ksf.us-east-2.rds.amazonaws.com:3306/digiboard_db?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xxxx
    password: xxxx
  liquibase:
    change-log: classpath:/db/changelogs/master-cl.yaml

springdoc:
  api-docs:
    path: /digiboard-api-docs-json #http://localhost:8080/digiboard-api-docs-json -> OpenAPI documentation in json format
  packages-to-scan: media.soft.controller
  swagger-ui:
    path: /digiboard-api-docs #http://localhost:8080/digiboard-api-docs -> Swagger documentation
    tryItOutEnabled: true
    operationsSorter: method
    tagsSorter: alpha
    filter: true
