# spring:
#   datasource:
#     url: jdbc:h2:mem:testdb
#     driver-class-name: org.h2.Driver
#     username: sa
#     password: password
#   h2:
#     console:
#       enabled: true
#       path: /h2-console
#   liquibase:
#     change-log: classpath:/db/changelogs/master-cl.yaml

spring:
  datasource:
    url: jdbc:hsqldb:mem:myDb
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    username: sa
    password: sa
  liquibase:
    change-log: classpath:/db/changelogs/master-cl.yaml

springdoc:
  api-docs:
    path: /digiboard-api-docs-json #http://localhost:8080/digiboard-api-docs-json -> OpenAPI documentation in json format
  packages-to-scan: media.soft.controller
  swagger-ui:
    path: /digiboard-api-docs #http://localhost:8080/digiboard-api-docs -> Swagger documentation
    tryItOutEnabled: true
    operationsSorter: method
    tagsSorter: alpha
    filter: true
